### ISSUE TITLE
cursor left/right sometimes stuck

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/SynLite#3]
3rd line in the text loaded by default
Ударе́ние

Start with the caret is before the "е́н". 
Press cursor right. Ok (caret between the 2 chars)
Press cursor right. Not ok (caret still between the 2 chars)
Press cursor right.  Ok (caret behind the 2 chars)

Likewise start behind the 2 chars and use caret left

**Comment by Alexey-T** [comment]
Hi here. It ok always: accent char after "e" is with 0 text width (it's SCalcCharOffset), so it's painted with Dx[i] 0 in textout. so caret stops on same space. i did skip of accent char before so caret don;t stop=== removed this coz it gave nasty code.. 

little prob now, VS nasty code

**Comment by Alexey-T** [comment]
we move here https://github.com/Alexey-T/ATSynEdit ...
