### ISSUE TITLE
SigFPE, small font, negative x spacing

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/SynLite#4]
Start the app.

Reduce font size to 6 (min allowed)
Reduce x spacing to -5 (it crashes at either -4 or -5)

#0 GETVISIBLECOLUMNS(0x29aff0) at ..\..\comp\atsynedit\atsynedit.pas:940
#1 UPDATEWRAPINFO(0x29aff0) at ..\..\comp\atsynedit\atsynedit.pas:863
#2 DOPAINTTO(0x29aff0, 0x2d9920) at ..\..\comp\atsynedit\atsynedit.pas:1137
#3 DOPAINT(0x29aff0, [CPAINTUPDATEBITMAP..CPAINTUPDATESCROLLBARS]) at ..\..\comp\atsynedit\atsynedit.pas:1920
#4 PAINT(0x29aff0) at ..\..\comp\atsynedit\atsynedit.pas:1942
#5 PAINTWINDOW(0x29aff0, 973152329) at include\customcontrol.inc:126
#6 PAINTHANDLER(0x29aff0, {MSG = 15, DC = 973152329, PAINTSTRUCT = 0x160fb50, RESULT = 0}) at include\wincontrol.inc:4744

**Comment by Alexey-T** [comment]
Easy to fix--thank, will fix
